"""
Base Strategy Interface and Registry
Provides the foundation for all deterministic strategy families.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    BOTH = "BOTH"


class Timeframe(str, Enum):
    TF_15M = "15m"
    TF_1H = "1h"
    TF_4H = "4h"


@dataclass
class SignalCandidate:
    """A candidate signal generated by a strategy."""
    symbol: str
    side: str  # "LONG" or "SHORT"
    entry_price: float
    stop_loss: float
    tp1: float
    tp2: float
    tp3: float
    confidence: int
    strategy_id: str
    strategy_version: str
    timeframe: str
    parameters: Dict[str, Any]
    conditions: List[str]
    invalidation_conditions: List[str]
    management_rules: List[str]
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """
    Abstract base class for all strategy families.
    All strategies must be deterministic and reproducible.
    """
    
    # Class attributes to be overridden by subclasses
    family: str = "base"
    supported_directions: List[str] = ["LONG", "SHORT"]
    supported_timeframes: List[str] = ["15m", "1h", "4h"]
    default_params: Dict[str, Any] = {}
    param_schema: Dict[str, Dict[str, Any]] = {}
    
    def __init__(self, config: Dict[str, Any], symbol: str):
        self.config = config
        self.symbol = symbol
        # Merge defaults with provided params
        self.params = {**self.default_params, **config.get("params", {})}
        self._validate_params()
    
    def _validate_params(self) -> None:
        """Validate strategy parameters against schema."""
        for param_name, schema in self.param_schema.items():
            if param_name in self.params:
                value = self.params[param_name]
                expected_type = schema.get("type")
                if expected_type == "int" and not isinstance(value, int):
                    raise ValueError(f"Parameter {param_name} must be int, got {type(value).__name__}")
                if expected_type == "float" and not isinstance(value, (int, float)):
                    raise ValueError(f"Parameter {param_name} must be float, got {type(value).__name__}")
                if expected_type == "bool" and not isinstance(value, bool):
                    raise ValueError(f"Parameter {param_name} must be bool, got {type(value).__name__}")
                min_val = schema.get("min")
                max_val = schema.get("max")
                if min_val is not None and value < min_val:
                    raise ValueError(f"Parameter {param_name} must be >= {min_val}, got {value}")
                if max_val is not None and value > max_val:
                    raise ValueError(f"Parameter {param_name} must be <= {max_val}, got {value}")
    
    @abstractmethod
    def generate_candidates(
        self,
        klines_15m: List[Dict[str, Any]],
        klines_1h: List[Dict[str, Any]],
        klines_4h: List[Dict[str, Any]],
        btc_regime: str,
        oi_data: Dict[str, Any],
        funding_rate: float,
        current_price: float,
    ) -> List[SignalCandidate]:
        """
        Generate signal candidates from market data.
        
        Args:
            klines_15m: 15-minute OHLCV candles (most recent last)
            klines_1h: 1-hour OHLCV candles
            klines_4h: 4-hour OHLCV candles
            btc_regime: BTC regime ("bullish", "bearish", "neutral")
            oi_data: Open Interest analysis result
            funding_rate: Current funding rate
            current_price: Current market price
            
        Returns:
            List of SignalCandidate objects (empty if no setup)
        """
        pass
    
    def get_param_grid(self) -> Dict[str, List]:
        """Return parameter grid for optimization. Override in subclass."""
        return {}


class StrategyRegistry:
    """Registry of all available strategy families and their instances."""
    
    def __init__(self):
        self._families: Dict[str, type] = {}
        self._instances: Dict[str, BaseStrategy] = {}
    
    def register_family(self, family_name: str, strategy_class: type) -> None:
        """Register a strategy family."""
        if not issubclass(strategy_class, BaseStrategy):
            raise ValueError(f"Strategy class must inherit from BaseStrategy")
        self._families[family_name] = strategy_class
    
    def create_instance(self, family: str, config: Dict[str, Any], symbol: str) -> BaseStrategy:
        """Create a strategy instance for a specific symbol."""
        if family not in self._families:
            raise ValueError(f"Unknown strategy family: {family}")
        return self._families[family](config, symbol)
    
    def get_family(self, family: str) -> Optional[type]:
        return self._families.get(family)
    
    def list_families(self) -> List[str]:
        """Return list of registered strategy family names."""
        return list(self._families.keys())
    
    def families(self) -> List[str]:
        """Return list of registered strategy family names (alias for list_families)."""
        return self.list_families()
    
    def __contains__(self, family: str) -> bool:
        return family in self._families
    
    def get(self, family: str) -> Optional[type]:
        """Get strategy class by family name."""
        return self._families.get(family)
    
    def create(self, family: str, config: Dict[str, Any], symbol: str) -> 'BaseStrategy':
        """Create a strategy instance."""
        if family not in self._families:
            raise ValueError(f"Unknown strategy family: {family}")
        return self._families[family](config, symbol)


# Global registry instance
STRATEGY_REGISTRY = StrategyRegistry()